FROM node:lts-alpine

WORKDIR /app

RUN apk add bash

COPY package.json /app

RUN npm install && npm install -g typescript && npm cache clean --force

EXPOSE 8080

CMD [ "npm", "run", "start:dev" ]